In [ ]:
#1
import numpy as np 
a = np.array([[3,4],[1,2]])
print(type(a))
a= a.tolist()
print(type(a))

In [ ]:
#2
a = np.array([[5,6,7,0],
              [2,5,4,9],
              [7,1,3,8],
              [6,7,9,8]])
sum = 0
j = 0
for i in a :
  sum = sum + i[j]
  j = j + 1
print(sum)

In [ ]:
#3
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = int(input())
for i in range(len(a)) :
  for j in range(len(a[0])) :
    if a[i,j] >= x :
      print(a[i,j])

In [35]:
#4
b = a
c = a + b
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
#5
import statistics as stat
b = np.array([[1,2,3],[4,4,5],[6,5,4]])
for i in range(len(b)) :
  m = stat.mean(b[i])
  for j in range(len(b[0])) :
    b[i,j] = b[i,j] - m